### ISSUE TITLE
Impostor

### ISSUE THREAD

**Issue by aleks-ivanov** [pipeline-foundation/projects#24]
## 1.  General Information

**Project Name:**  Impostor

**GitHub URL:**  https://github.com/Impostor/Impostor

## 2.  Description

Impostor - An open source reimplementation of the Among Us Server

## 3.  Contact Person

**Name:**  

**Email:**  

**GitHub Profile URL:**  

## 4.  Eligibility Criteria

Please complete the following for your project:

* Project has build instructions.
- [x] Yes
* Project has semantic versioning.
- [x] Yes
* Project has dependencies management.
- [ ] Yes
* Project has automated tests.
- [ ] Yes
* Project has code quality analysis.
- [ ] Yes
* Project has code security scanning.
- [ ] Yes
* Project has secrets management.
- [ ] Yes
* Project has GitHub releases.
- [x] Yes
* Project has artifacts publishing.
- [x] Yes
* Project has automated deployment.
- [x] Yes

**Comment by AeonLucid** [comment]
No thank you.
